---
- name: deploy Open Stack controler
  hosts: 192.168.122.68
  user: root
  sudo: yes
  gather_facts: True
  vars:
   - files: files/
   - private: private/
   - endpoint: http://controller:35357/v2.0

  vars_files:
   - vars/os.yml
   - vars/ip.yml

  tasks:
#  - name: Set the hostname
#    action: shell hostname os-controler

  - name: install core pkgs
    action: yum state=present pkg={{ item }}
    with_items:
    - libselinux-python
    - ntp

  - name: disable selinux
    action: selinux policy=targeted state=permissive

  - lvg: vg=cinder-volumes pvs=/dev/vdb pesize=32

  - template: src={{ files }}/hosts dest=/etc/hosts owner=root mode=0644

  # http://docs.openstack.org/trunk/install-guide/install/yum/content/basics-networking.html
  #- service: name=NetworkManager state=stopped enabled=no
  - service: name=network state=started enabled=yes
  #- service: name=firewalld state=stopped enabled=no
  - service: name=iptables state=started enabled=yes

  # http://docs.openstack.org/trunk/install-guide/install/yum/content/basics-neutron-networking-controller-node.html
  - lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth1 regexp="^ONBOOT=" line="ONBOOT=yes"
  - lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth1 regexp="^NETMASK=" line="NETMASK=255.255.255.0"
  - lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth1 regexp="^IPADDR=" line="IPADDR={{controller_private_ip}}"
  - lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth1 regexp="BOOTPROTO=" line="BOOTPROTO=none"
  # FIXME notify network service restart

  # http://docs.openstack.org/trunk/install-guide/install/yum/content/basics-ntp.html
  - service: name=ntpd state=started enabled=yes

  # http://openstack.redhat.com/Quickstart
  - yum: state=present name=http://rdo.fedorapeople.org/rdo-release.rpm
  - yum: state=present name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
  - yum: state=present name=openstack-utils
  - yum: state=present name=openstack-selinux
  - yum: state=present name=openstack-packstack
  - yum: name=* state=latest

  - template: src={{ files }}/packstack-answers.txt dest=/root/ owner=root mode=0600
  - authorized_key: user=root key="ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA4psdzreoSp8aQfrZtfNSDqPsJNFXiTmmu1QSo7ToCVI06bEH+Sjtynkkno1V/cGGRpD3GEdjcPgFeGOwXol1RcmxV9pe8IuIsnlLpykJoSxV93jJJ34IXqPAop5VMH0rdVOyRBHdcYORVcO4PTqmKHFeLdFDiqNUwqKVGx1nL64fUL0sVafpsn4ORWoD6YU6Jk8P0k/20fAu+XpEBnYkOsxQoUbaAF5GPw0UdPjF48IB9bTJDcdnLb9hmNkVzaSpNRLqeCj+7hFm558TVdwuLy+Aiomz5QhsBOj/iad6p5mdL1cmbOkL1BmeZAs2978Ly4ZmPQAfjPtzAjefUZOj1w== root@os-controler"
  - command: packstack --answer-file=/root/packstack-answers.txt


  # http://docs.openstack.org/trunk/install-guide/install/yum/content/glance-verify.html
  - get_url: url=http://cdn.download.cirros-cloud.net/0.3.2/cirros-0.3.2-x86_64-disk.img dest=/root/cirros-0.3.2-x86_64-disk.img mode=0440
  - shell: source /root/keystonerc_admin && glance image-list |grep "cirros-0.3.2-x86_64" || glance image-create --name=cirros-0.3.2-x86_64 --disk-format=qcow2 --container-format=bare --is-public=True < /root/cirros-0.3.2-x86_64-disk.img

  - shell: source /root/keystonerc_admin && nova image-list


